name: Publish to pub.dev

# This workflow will publish the package to pub.dev when a new tag is pushed
on:
  push:
    branches:
      - main
    

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable
          channel: stable
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Verify package
        run: flutter pub publish --dry-run
        
      - name: Run tests
        run: flutter test
        
      - name: Check formatting
        run: dart format -o none . --set-exit-if-changed
        
      - name: Analyze code
        run: flutter analyze --fatal-infos
        
      - name: pub.dev credentials
        run: |
          mkdir -p $HOME/.config/dart
          echo '${{ secrets.PUB_JSON }}' >> $HOME/.config/dart/pub-credentials.json
          
      - name: Publish to pub.dev
        run: flutter pub publish --force